name: aws-s3-cloudfront
description: 'aws s3 & cloudfront'
author: 'comori'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'life-buoy'
  color: 'red'

# Define your inputs here.
inputs:
  aws-access-key-id:
    description: "AWS access key id to access your bucket"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key to access your bucket"
    required: true
  aws-region:
    description: "AWS region where your bucket is located"
    required: true
    default: us-east-1
  bucket:
    description: "AWS s3 bucket to store the artifacts"
    required: true
  source-files:
    description: 'Your sourceFiles here'
    required: true
  target-dir:
    description: 's3 targetDir'
    required: true
  invalidation-path:
    description: 'invalidation path list'
    required: false
  distribution-id:
    description: 'Cloudfront distribution id'
    required: false
  
  

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
